-- Create additional_scopes table
CREATE TABLE IF NOT EXISTS public.additional_scopes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    scope_category TEXT NOT NULL,
    scope_code TEXT NOT NULL UNIQUE,
    scope_of_work TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_additional_scopes_user_id ON public.additional_scopes(user_id);
CREATE INDEX IF NOT EXISTS idx_additional_scopes_scope_code ON public.additional_scopes(scope_code);
CREATE INDEX IF NOT EXISTS idx_additional_scopes_category ON public.additional_scopes(scope_category);

-- Function to generate unique 4-digit scope code
CREATE OR REPLACE FUNCTION public.generate_unique_scope_code()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_code TEXT;
    code_exists BOOLEAN;
    max_attempts INTEGER := 100;
    attempt_count INTEGER := 0;
BEGIN
    LOOP
        -- Generate random 4-digit number (1000-9999)
        new_code := LPAD(FLOOR(RANDOM() * 9000 + 1000)::TEXT, 4, '0');
        
        -- Check if code already exists
        SELECT EXISTS(
            SELECT 1 FROM public.additional_scopes WHERE scope_code = new_code
        ) INTO code_exists;
        
        -- If code doesn't exist, return it
        IF NOT code_exists THEN
            RETURN new_code;
        END IF;
        
        -- Increment attempt counter
        attempt_count := attempt_count + 1;
        
        -- Prevent infinite loop
        IF attempt_count >= max_attempts THEN
            RAISE EXCEPTION 'Unable to generate unique scope code after % attempts', max_attempts;
        END IF;
    END LOOP;
END;
$$;

-- Trigger function to auto-generate scope_code before insert
CREATE OR REPLACE FUNCTION public.set_scope_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Only generate if scope_code is not provided or is empty
    IF NEW.scope_code IS NULL OR NEW.scope_code = '' THEN
        NEW.scope_code := public.generate_unique_scope_code();
    END IF;
    RETURN NEW;
END;
$$;

-- Create trigger to auto-generate scope_code
DROP TRIGGER IF EXISTS trigger_set_scope_code ON public.additional_scopes;
CREATE TRIGGER trigger_set_scope_code
    BEFORE INSERT ON public.additional_scopes
    FOR EACH ROW
    EXECUTE FUNCTION public.set_scope_code();

-- Enable RLS
ALTER TABLE public.additional_scopes ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "users_manage_own_additional_scopes" ON public.additional_scopes;
CREATE POLICY "users_manage_own_additional_scopes"
ON public.additional_scopes
FOR ALL
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Mock data
DO $$
DECLARE
    existing_user_id UUID;
BEGIN
    -- Get existing user
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'user_profiles'
    ) THEN
        SELECT id INTO existing_user_id FROM public.user_profiles LIMIT 1;
        
        IF existing_user_id IS NOT NULL THEN
            -- Insert sample scopes (scope_code will be auto-generated by trigger)
            INSERT INTO public.additional_scopes (user_id, scope_category, scope_code, scope_of_work, description)
            VALUES 
                (existing_user_id, 'site_preparation', '', 'Site clearing and preparation', 'Complete site preparation including excavation and grading'),
                (existing_user_id, 'landscaping', '', 'Landscaping and outdoor features', 'Installation of landscaping, irrigation, and outdoor amenities'),
                (existing_user_id, 'security_systems', '', 'Security system installation', 'Complete security system including cameras and access control')
            ON CONFLICT (scope_code) DO NOTHING;
        ELSE
            RAISE NOTICE 'No existing users found. Run auth migration first.';
        END IF;
    ELSE
        RAISE NOTICE 'Table user_profiles does not exist. Run auth migration first.';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Mock data insertion failed: %', SQLERRM;
END $$;