-- Create external_trades table
CREATE TABLE IF NOT EXISTS public.external_trades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    trade_category TEXT NOT NULL,
    trade_code TEXT NOT NULL UNIQUE,
    scope_of_work TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_external_trades_user_id ON public.external_trades(user_id);
CREATE INDEX IF NOT EXISTS idx_external_trades_trade_code ON public.external_trades(trade_code);
CREATE INDEX IF NOT EXISTS idx_external_trades_category ON public.external_trades(trade_category);

-- Function to generate unique 4-digit trade code
CREATE OR REPLACE FUNCTION public.generate_unique_trade_code()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_code TEXT;
    code_exists BOOLEAN;
    max_attempts INTEGER := 100;
    attempt_count INTEGER := 0;
BEGIN
    LOOP
        -- Generate random 4-digit number (1000-9999)
        new_code := LPAD(FLOOR(RANDOM() * 9000 + 1000)::TEXT, 4, '0');
        
        -- Check if code already exists
        SELECT EXISTS(
            SELECT 1 FROM public.external_trades WHERE trade_code = new_code
        ) INTO code_exists;
        
        -- If code doesn't exist, return it
        IF NOT code_exists THEN
            RETURN new_code;
        END IF;
        
        -- Increment attempt counter
        attempt_count := attempt_count + 1;
        
        -- Prevent infinite loop
        IF attempt_count >= max_attempts THEN
            RAISE EXCEPTION 'Unable to generate unique trade code after % attempts', max_attempts;
        END IF;
    END LOOP;
END;
$$;

-- Trigger function to auto-generate trade_code before insert
CREATE OR REPLACE FUNCTION public.set_trade_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Only generate if trade_code is not provided or is empty
    IF NEW.trade_code IS NULL OR NEW.trade_code = '' THEN
        NEW.trade_code := public.generate_unique_trade_code();
    END IF;
    RETURN NEW;
END;
$$;

-- Create trigger to auto-generate trade_code
DROP TRIGGER IF EXISTS trigger_set_trade_code ON public.external_trades;
CREATE TRIGGER trigger_set_trade_code
    BEFORE INSERT ON public.external_trades
    FOR EACH ROW
    EXECUTE FUNCTION public.set_trade_code();

-- Enable RLS
ALTER TABLE public.external_trades ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "users_manage_own_external_trades" ON public.external_trades;
CREATE POLICY "users_manage_own_external_trades"
ON public.external_trades
FOR ALL
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Mock data
DO $$
DECLARE
    existing_user_id UUID;
BEGIN
    -- Get existing user
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'user_profiles'
    ) THEN
        SELECT id INTO existing_user_id FROM public.user_profiles LIMIT 1;
        
        IF existing_user_id IS NOT NULL THEN
            -- Insert sample trades (trade_code will be auto-generated by trigger)
            INSERT INTO public.external_trades (user_id, trade_category, trade_code, scope_of_work, description)
            VALUES 
                (existing_user_id, 'electrical', '', 'Install electrical wiring and fixtures', 'Complete electrical installation for new building'),
                (existing_user_id, 'plumbing', '', 'Install plumbing systems and fixtures', 'Full plumbing system installation including water supply and drainage'),
                (existing_user_id, 'hvac', '', 'Install HVAC systems', 'Heating, ventilation, and air conditioning system installation')
            ON CONFLICT (trade_code) DO NOTHING;
        ELSE
            RAISE NOTICE 'No existing users found. Run auth migration first.';
        END IF;
    ELSE
        RAISE NOTICE 'Table user_profiles does not exist. Run auth migration first.';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Mock data insertion failed: %', SQLERRM;
END $$;